'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class MvcCrudEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MvcCrudEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Tbl_department() As DbSet(Of Tbl_department)
    Public Overridable Property tbl_StudentID() As DbSet(Of tbl_StudentID)

End Class
