'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_department
    Public Property department As Integer
    Public Property DepartmentName As String

    Public Overridable Property tbl_StudentID As ICollection(Of tbl_StudentID) = New HashSet(Of tbl_StudentID)

End Class
