'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_StudentID
    Public Property StudentID As Integer
    Public Property StudentName As String
    Public Property Email As String
    Public Property IsDeleted As Nullable(Of Boolean)
    Public Property DepartmentID As Nullable(Of Integer)

    Public Overridable Property Tbl_department As Tbl_department

End Class
